name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Compilar con Maven
        run: mvn clean package

      - name: Build y empujar imagen Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t xmathyu/demo-devops:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push xmathyu/demo-devops:latest

      - name: Configurar Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.21.0'  # Cambia a la versión de Kubectl que necesites

      - name: Desplegar en Kubernetes
        run: kubectl apply -f DevOps/k8s.yaml